config/routes.rb
Rails.application.routes.draw do
  devise_for :passengers
  root 'welcome#welcome'

  resources 'flights'

  get '/find-flights' => 'flights#find', as: :find_flights
  post '/find-flights', to: 'flights#found', as: "found_flights"

  post '/reservations' => 'reservations#create', as: :create_reservation

    resources 'passengers', only: :show do
      resources 'reservations'
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :reservations
  has_many :passengers, through: :reservations

  scope :query_flights, ->(query) {where("departure_city = ? AND arrival_city = ? AND date = ?", query[:from].downcase, query[:to].downcase, query[:depart_date])}
end

app/models/passenger.rb
class Passenger < ApplicationRecord

  has_many :reservations
  has_many :flights, through: :reservations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def find
    @query = params.permit(:from, :to, :depart_date)
    @date = Date.parse(@query[:depart_date]).strftime("%A, %B %e %Y")

    @flights = Flight.query_flights(@query)
    
    render 'flights'
  end

  def found
  end

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
  end

  def show
  end

  def edit
  end

  def destroy
  end

  def update
  end

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flights/flights.html.erb
<h2><%="#{@query[:from]} > #{@query[:to]}"%></h2>
<p>
  <%= @date %>
</p>
<% if @flights.any? %>
  <% @flights.each do |flight| %>
    <div class="flight">
      <%= "FA #{flight.id}" %>  <br>
      <%= "#{flight.departure_time} > #{flight.arival_time}" %> <br> <br>
      <%=number_to_currency(flight.price) %>
    </div>
    <br>
    <% end %>
  <% else %>
  <p>There were no flights available on the given days. <%= link_to "Refine your Search", root_path %> </p>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatAirlines</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/welcome.html.erb
<h1>FlatAir</h1>
<h3>Threre is no better way to fly!</h3>

<main>
  <p>Book a flight
    <%= form_tag(found_flights_path, method: :get) do %>
    <div class="">
      <%= label_tag 'from', "FROM" %><br>
      <%= text_field_tag 'from', nil, placeholder: "City" %>
    </div>
    <div class="">
      <%= label_tag 'to', "TO" %><br>
      <%= text_field_tag 'to', nil, placeholder: "City" %>
    </div>
    <div class="">
      <%= label_tag 'depart_date', "DEPART DATE" %><br>
       <%= date_field_tag "depart_date" %>
    </div>
    <br>
    <div class="">
      <%= submit_tag "Find Flights" %>
    </div>


     <%end%>
  </p>
</main>